server:
  port: 17060
spring:
  config:
    import:
      - optional:configserver:http://61.102.114.235:8888
  kafka:
    bootstrap-servers: 192.168.0.31:9092
eureka:
  client:
    enabled: false
    register-with-eureka: false  # Eureka 서버에 등록하지 않음
    fetch-registry: false        # 레지스트리를 가져오지 않음